<a href="https://colab.research.google.com/github/naviatolin/college_admissions/blob/main/FinalML_Project_Happiness_Trends.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Patrick Ogunbufunmi, Walter Villa & Navi Boyalakuntla 

### Topic: Happiness Trends and effects in Demographics over time

**Question**: How will the demographics of some colleges change over time based on personal characteristics

**Inspiration**: Bias in College

In [1]:
from google.colab import drive
drive.mount("/content/drive", force_remount = True)

Mounted at /content/drive


#Importing Dataset

In [2]:
import gdown
import numpy as np
import pandas as pd
df = pd.read_csv("drive/MyDrive/mock_student_data - Sheet1.csv")
print(df.head())

   Male  Female  NB  ...  Sexuality.1  Unnamed: 23  College Choice
0     0       1   0  ...        LGBTQ    Not LGBTQ               3
1     1       0   0  ...          0.3          0.7               3
2     0       1   0  ...          0.5          0.5               3
3     0       1   0  ...         0.01         0.99               3
4     1       0   0  ...          NaN          NaN               3

[5 rows x 25 columns]


## Removing unecessary properties and Parsing Data

In [3]:
properties = list(df.columns.values)

properties.remove('H_C1')
properties.remove('H_C2')
properties.remove('H_C3')
properties.remove('Unnamed: 14')
properties.remove('Gender')
properties.remove('Unnamed: 16')
properties.remove('Unnamed: 17')
properties.remove('Unnamed: 18')
properties.remove('Race')
properties.remove('Unnamed: 20')
properties.remove('Unnamed: 21')
properties.remove('Sexuality.1')
properties.remove('Unnamed: 23')
properties.remove('College Choice')
print(properties)
X = df[properties]
y = df[['H_C1','H_C2','H_C3']]

['Male', 'Female', 'NB', 'White', 'Black', 'Asian', 'Latina', 'Native-American', 'Sexuality', 'SAT', 'GPA']


## Splitting Data 
Here we split our data into our training set, testing set, as well as data to run our trained model on.

In [4]:
import tensorflow as tf
import tensorflow 

from tensorflow import keras
from keras.layers import Dense
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.75, random_state=1)



# **Defining Model Parameters**
Here we create our CNN, as well as define what parameters to pass to our Neural Network defined at the end, such as batch size, learning rate, etc

In [5]:
print(X_train.head())
print(X_test.head())
print(X_val.head())

     Male  Female  NB  White  ...  Native-American  Sexuality   SAT   GPA
810     1       0   0      0  ...                0          1  1382  3.61
570     1       0   0      0  ...                0          1  1064  1.31
813     1       0   0      1  ...                1          1  1474  3.35
837     1       0   0      1  ...                1          1   531  3.65
669     0       1   0      0  ...                0          1  1286  3.65

[5 rows x 11 columns]
     Male  Female  NB  White  ...  Native-American  Sexuality   SAT   GPA
478     0       1   0      1  ...                1          1   930  1.95
301     0       1   0      1  ...                0          1   709  4.24
576     0       1   0      1  ...                0          0   940  5.00
851     1       0   0      0  ...                0          1  1304  4.36
496     1       0   0      0  ...                0          0  1411  2.51

[5 rows x 11 columns]
      Male  Female  NB  White  ...  Native-American  Sexuality   S

In [6]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(11,)),
    keras.layers.Dense(33, activation=tf.nn.relu),
    keras.layers.Dense(33, activation=tf.nn.relu),
    ##keras.layers.Dense(33, activation=tf.nn.relu),
   ## keras.layers.Dense(33, activation=tf.nn.relu),
   	keras.layers.Dense(33, activation=tf.nn.relu),
    keras.layers.Dense(3, activation=tf.nn.sigmoid),
])

# **Model Training**


Our convolutional network has the following layer structure:

- Dimensionality Flattening
- Activation function (ReLU)
- Fully connected layer
- Activation function (ReLU)
- Sigmoid Layer.

We start off with flattening our input shape to pass into our fully connected layer, followed by a fully connected layer to perform some logic computations on those features, and finally a fully connected layer to turn those outputs into predictions for the class. The optimization algorithm we use to train our model is Mini-batch Gradient Descent. The model iterates through mini-batches of the dataset, each time estimating the gradient and then performing an update step. These batches are used to calculate the error of the model and update model coefficients. At the end of each epoch, which is when the model has run through all the batches, the model is passed through the test set and the validation loss is calculated and printed.

In [7]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=800, batch_size=10)
test_loss, test_acc = model.evaluate(X_test, y_test)


Epoch 1/800
15/15 [==============================] - 1s 2ms/step - loss: 16.4545 - accuracy: 0.1216
Epoch 2/800
15/15 [==============================] - 0s 2ms/step - loss: 2.8102 - accuracy: 0.1959
Epoch 3/800
15/15 [==============================] - 0s 2ms/step - loss: 1.0575 - accuracy: 0.4324
Epoch 4/800
15/15 [==============================] - 0s 2ms/step - loss: 0.7234 - accuracy: 0.3378
Epoch 5/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6753 - accuracy: 0.3716
Epoch 6/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6598 - accuracy: 0.4257
Epoch 7/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6570 - accuracy: 0.3784
Epoch 8/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6584 - accuracy: 0.3108
Epoch 9/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6616 - accuracy: 0.3716
Epoch 10/800
15/15 [==============================] - 0s 2ms/step - loss: 0.6553 - accuracy: 0.3514
Epoch 11

In [8]:
print('Test accuracy:', test_acc)

Test accuracy: 0.9006733894348145


In [9]:
##TODO: Make df of predicted admit of validation set
v_predict = model.predict(X_val)
print(v_predict)

[[0.2527864  0.38082537 0.12595904]
 [0.43691906 0.47465456 0.35852247]
 [0.38958186 0.39868897 0.38013473]
 ...
 [0.2270143  0.22486454 0.3108803 ]
 [0.3658371  0.32332766 0.35747498]
 [0.51397216 0.49137673 0.6450041 ]]


## Adding Predicted Happiness to DataFrame

In [10]:
#append array into dataframe for Xval
Happiness_Scores = pd.DataFrame(v_predict)
Happiness_Scores.columns =[['HCP_1','HCP_2','HCP_3']]

In [11]:
Happiness_Scores.head()

HCP_1     HCP_2     HCP_3
0  0.252786  0.380825  0.125959
1  0.436919  0.474655  0.358522
2  0.389582  0.398689  0.380135
3  0.389728  0.324068  0.350935
4  0.595341  0.501139  0.650113

In [12]:
#append to original dataset
trg_data = pd.concat([X_val], ignore_index=True)
X_new = trg_data.join(Happiness_Scores)
print(X_new)

     Male  Female  NB  White  Black  ...   SAT   GPA  (HCP_1,)  (HCP_2,)  (HCP_3,)
0       0       1   0      0      1  ...   228  3.65  0.252786  0.380825  0.125959
1       0       1   0      1      1  ...   341  2.40  0.436919  0.474655  0.358522
2       0       1   0      1      0  ...  1340  3.23  0.389582  0.398689  0.380135
3       0       1   0      1      1  ...   612  4.79  0.389728  0.324068  0.350935
4       1       0   0      1      1  ...  1394  1.73  0.595341  0.501139  0.650113
..    ...     ...  ..    ...    ...  ...   ...   ...       ...       ...       ...
440     1       0   0      1      1  ...  1257  1.76  0.429390  0.338685  0.638088
441     1       0   0      0      1  ...   431  2.98  0.318989  0.410405  0.313874
442     1       0   0      0      0  ...  1014  3.06  0.227014  0.224865  0.310880
443     0       1   0      1      0  ...   568  3.28  0.365837  0.323328  0.357475
444     1       0   0      1      1  ...  1074  3.71  0.513972  0.491377  0.645004

[44

In [13]:
#TO:DO Use highest happiness to choose students college and update demographic with time
#Choos ebased on probabalistic distribution model
#random.choices(DataFrame, weights=Happiness, k=1)
#Take batch of students and update college demographic sheet
#Remove them and recalculate happiness of each student
#Run model again
#Look at demographics
